server:
  port: 8080

spring:
  application:
    name: SmartFXApplication

# OpenAPI/Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Logging configuration
logging:
  level:
    root: INFO
    com.plozdev.smartfxapplication: DEBUG
